import Head from "next/head"
import styles from '../../styles/Movies.module.css'
import { useState, useEffect, useReducer } from "react"
import TopMenu from "../../components/TopMenu"
import MoviesSort from "../../components/MoviesSort"
import MoviesFilterSide from "../../components/MoviesFilterSide"
import SingleLine from "../../components/lists/SingleLine"
import Layout from "../../components/Layout"
import useSWRInfinite from "swr"
import InfoButton from "../../components/InfoButton"
import { takeCoverage } from "v8"

const fetcher = url => fetch(url).then(r => r.json())

// filter On / Off
function helperReducer(arrState, action) {
	let arr = arrState;
	if(action.payload.checked) {
		arr.push(action.payload.value)
	} else {
		arr = arr.filter(el => el !== action.payload.value)
	}
	return arr 
}

function helperQuery(arr,type) {
	let output

	if(type === 'rating') {


		return
	} else if(arr.length > 1) {
		output = arr.map(el => el).join('+')
		return `${type}=${output}`
	} else if(arr.length === 1) {
		return `${type}=${arr[0]}`
	} else {
		return ''
	}
}

function reducer(state, action) {
	let arr
	switch(action.type) {
		case "title":
			arr = helperReducer(state.title, action)
			return {
				...state,
				title: arr
			};
		case "genre":
			arr = helperReducer(state.genre, action)
			return {
				...state,
				genre: arr
			};
		case "decade":
			arr = helperReducer(state.decade, action)
			return {
				...state,
				decade: arr
			};
		default:
			return state;
	}
}

const initialState = {
	title: '',
	genre: [],
	decade: []
}

const Movies = () => {
	const [displayCovers, setDisplayCover] = useState(true);
	const [state, dispatch] = useReducer(reducer, initialState);
	const [activeSort, setActiveSort] = useState('');

	const urlGenre = helperQuery(state.genre, 'genre')
	const urlDecade = helperQuery(state.decade, 'decade')

	

	const url = `/api/movies?${urlGenre}&${urlDecade}`
	const { data: searchData, error: searchError } = useSWRInfinite(url, fetcher);

	console.log({activeSort, url})
	// console.log(searchData)

	function handleSortInput(button) {
		if(activeSort === button) {
			setActiveSort('')
		} else {
			setActiveSort(button)
		}
	}

	function handleFilters(data) {
		const filterType = data.entry.split('-')[0];

		dispatch({
			type: filterType,
			payload: {
				checked: data.checked, 
				value: data.entry.split('-')[1]
			}
		})
	}

	function deleteFilter(tag,type) {
		dispatch({
			type: type,
			payload: {
				checked: false,
				value: tag
			}
		})
	}
	
	// Later we should retrieve all available genres from existing movies in the database
	const genres = ['action','animation', 'comedy','drama','fantasy','horror','romance','sciencefiction','thriller','war']
	const decades = ['1970s','1980s','1990s','2000s','2010s','2020s']


	return (
		<>
			<Head>
				<title>Movies</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<TopMenu />

			<div className={styles.containerContent}>
				<div className={styles.contentWrap}>

					<section id={styles.filterSide}>
						
						<span>Active filters</span>
						
						<div className={styles.activeFilters}>
							{ state.genre.map((entry, i) => { 
								return <InfoButton key={`genre-${i}`} 
									text={entry} 
									type='genre'
									canDelete={true}
									callback={deleteFilter}/> })
							}
							{ state.decade.map((entry, i) => {
								return <InfoButton 
									key={`decade-${i}`} 
									text={entry}
									type='decade' 
									canDelete={true}
									callback={deleteFilter}/>})
							}
						</div>
						
						<MoviesFilterSide name='Genre' options={genres} handleFilters={handleFilters} state={state.genre} activeLimit={3}/>
						<MoviesFilterSide name='Decade' options={decades} handleFilters={handleFilters} state={state.decade} activeLimit={1} />
					</section>
					
					<section id={styles.right}>
						<div id={styles.filterTop}>
							<MoviesSort activeSort={activeSort} callBack={handleSortInput}/>
						</div>
					
						<div id={styles.movieItems}>
							{
								searchData &&
								<SingleLine data={searchData.movies} type='detail' />

							}

						</div>
					</section>



				</div>
			</div>



		</>
	)
}

export default Movies