import styles from '../../styles/admin/Admin.module.css'
import Head from 'next/head'
import { collection, getDocs } from 'firebase/firestore'
import { projectFirestore, projectStorage } from '../../firebase/clientApp'
import { useEffect, useState } from 'react'
import Entries from '../../components/admin/Entries'
import CreateMovie from '../../components/admin/CreateMovie'
import useFetchMovies from '../../hooks/useFetchMovies'

const Admin = () => {
	const {isFetching, movies} = useFetchMovies()

	return (
		<>
		<Head>
			<title>Movies</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>


		<div className={styles.container}>
			<Head>
				<title>Movies - Admin</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<CreateMovie />

			<Entries movies={movies}/>

		</div>
		</>
	)
}

export default Admin